/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepresentativesRouteImport } from './routes/representatives'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturedProductsRouteImport } from './routes/featured-products'
import { Route as FactoryOrdersRouteImport } from './routes/factory-orders'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as UsersRouteImport } from './routes/Users'
import { Route as FactoriesRouteImport } from './routes/Factories'
import { Route as FAQRouteImport } from './routes/FAQ'
import { Route as CashBackRouteImport } from './routes/CashBack'
import { Route as BannersRouteImport } from './routes/Banners'
import { Route as IndexRouteImport } from './routes/index'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentativesRoute = RepresentativesRouteImport.update({
  id: '/representatives',
  path: '/representatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedProductsRoute = FeaturedProductsRouteImport.update({
  id: '/featured-products',
  path: '/featured-products',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryOrdersRoute = FactoryOrdersRouteImport.update({
  id: '/factory-orders',
  path: '/factory-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/Users',
  path: '/Users',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoriesRoute = FactoriesRouteImport.update({
  id: '/Factories',
  path: '/Factories',
  getParentRoute: () => rootRouteImport,
} as any)
const FAQRoute = FAQRouteImport.update({
  id: '/FAQ',
  path: '/FAQ',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBackRoute = CashBackRouteImport.update({
  id: '/CashBack',
  path: '/CashBack',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/Banners',
  path: '/Banners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Banners': typeof BannersRoute
  '/CashBack': typeof CashBackRoute
  '/FAQ': typeof FAQRoute
  '/Factories': typeof FactoriesRoute
  '/Users': typeof UsersRoute
  '/analytics': typeof AnalyticsRoute
  '/factory-orders': typeof FactoryOrdersRoute
  '/featured-products': typeof FeaturedProductsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/representatives': typeof RepresentativesRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Banners': typeof BannersRoute
  '/CashBack': typeof CashBackRoute
  '/FAQ': typeof FAQRoute
  '/Factories': typeof FactoriesRoute
  '/Users': typeof UsersRoute
  '/analytics': typeof AnalyticsRoute
  '/factory-orders': typeof FactoryOrdersRoute
  '/featured-products': typeof FeaturedProductsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/representatives': typeof RepresentativesRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Banners': typeof BannersRoute
  '/CashBack': typeof CashBackRoute
  '/FAQ': typeof FAQRoute
  '/Factories': typeof FactoriesRoute
  '/Users': typeof UsersRoute
  '/analytics': typeof AnalyticsRoute
  '/factory-orders': typeof FactoryOrdersRoute
  '/featured-products': typeof FeaturedProductsRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/representatives': typeof RepresentativesRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Banners'
    | '/CashBack'
    | '/FAQ'
    | '/Factories'
    | '/Users'
    | '/analytics'
    | '/factory-orders'
    | '/featured-products'
    | '/login'
    | '/orders'
    | '/products'
    | '/representatives'
    | '/settings'
    | '/stores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Banners'
    | '/CashBack'
    | '/FAQ'
    | '/Factories'
    | '/Users'
    | '/analytics'
    | '/factory-orders'
    | '/featured-products'
    | '/login'
    | '/orders'
    | '/products'
    | '/representatives'
    | '/settings'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/Banners'
    | '/CashBack'
    | '/FAQ'
    | '/Factories'
    | '/Users'
    | '/analytics'
    | '/factory-orders'
    | '/featured-products'
    | '/login'
    | '/orders'
    | '/products'
    | '/representatives'
    | '/settings'
    | '/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannersRoute: typeof BannersRoute
  CashBackRoute: typeof CashBackRoute
  FAQRoute: typeof FAQRoute
  FactoriesRoute: typeof FactoriesRoute
  UsersRoute: typeof UsersRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FactoryOrdersRoute: typeof FactoryOrdersRoute
  FeaturedProductsRoute: typeof FeaturedProductsRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  RepresentativesRoute: typeof RepresentativesRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representatives': {
      id: '/representatives'
      path: '/representatives'
      fullPath: '/representatives'
      preLoaderRoute: typeof RepresentativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured-products': {
      id: '/featured-products'
      path: '/featured-products'
      fullPath: '/featured-products'
      preLoaderRoute: typeof FeaturedProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory-orders': {
      id: '/factory-orders'
      path: '/factory-orders'
      fullPath: '/factory-orders'
      preLoaderRoute: typeof FactoryOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Users': {
      id: '/Users'
      path: '/Users'
      fullPath: '/Users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Factories': {
      id: '/Factories'
      path: '/Factories'
      fullPath: '/Factories'
      preLoaderRoute: typeof FactoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FAQ': {
      id: '/FAQ'
      path: '/FAQ'
      fullPath: '/FAQ'
      preLoaderRoute: typeof FAQRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CashBack': {
      id: '/CashBack'
      path: '/CashBack'
      fullPath: '/CashBack'
      preLoaderRoute: typeof CashBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Banners': {
      id: '/Banners'
      path: '/Banners'
      fullPath: '/Banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannersRoute: BannersRoute,
  CashBackRoute: CashBackRoute,
  FAQRoute: FAQRoute,
  FactoriesRoute: FactoriesRoute,
  UsersRoute: UsersRoute,
  AnalyticsRoute: AnalyticsRoute,
  FactoryOrdersRoute: FactoryOrdersRoute,
  FeaturedProductsRoute: FeaturedProductsRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  RepresentativesRoute: RepresentativesRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
